In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('../../Datasets/car price/CarPrice_Assignment.csv')

In [3]:
df = pd.read_csv('../../Datasets/car price/CarPrice_Assignment.csv')
df = df.drop('car_ID', axis=1)
df = df.drop('CarName', axis=1)

In [5]:
df.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [9]:
binary_columns = []
categorical_columns = []

for c in df.columns:
    if df[c].dtype == 'object':
        if len(df[c].value_counts()) == 2:
            binary_columns.append(c)
        if len(df[c].value_counts()) > 2:
            categorical_columns.append(c)

In [49]:
print(binary_columns)
print(categorical_columns)

['aspiration', 'doornumber', 'enginelocation']
['carbody', 'drivewheel', 'enginetype', 'cylindernumber', 'fuelsystem']

In [10]:
df = pd.get_dummies(df, prefix=binary_columns, columns=binary_columns , drop_first=True)
df = pd.get_dummies(df, prefix=categorical_columns, columns=categorical_columns)

In [11]:
df.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,0,0,1,0,0
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,0,0,1,0,0
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0,0,0,0,0,0,0,1,0,0
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0,0,0,0,0,0,0,1,0,0
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0,0,0,0,0,0,0,1,0,0

In [12]:
y = df.price.to_numpy()
df = df.drop('price', axis=1)
X = df.to_numpy()

In [14]:
p = np.random.permutation(X.shape[0])

X = X[p]
y = y[p]

In [17]:
split1 = int(X.shape[0] * 0.6)
split2 = int(X.shape[0] * 0.8)

X_train = X[:split1]
X_val = X[split1:split2]
X_test = X[split2:]

y_train = y[:split1]
y_val = y[split1:split2]
y_test = y[split2:]

In [19]:
print(X_train.shape, X_val.shape, X_test.shape)

(123, 48) (41, 48) (41, 48)

In [20]:
mean_train = X_train.mean(axis=0)
std_train = X_train.std(axis=0)

X_train = (X_train - mean_train) / std_train
X_val = (X_val - mean_train) / std_train
X_test = (X_test - mean_train) / std_train

In [21]:
np.save('X_train.npy', X_train)
np.save('X_val.npy', X_val)
np.save('X_test.npy', X_test)

In [22]:
X_train = np.load('X_train.npy')
X_val = np.load('X_val.npy')
X_test = np.load('X_test.npy')

In [23]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
clf = KNeighborsRegressor()

clf.fit()